# Generated by Django 4.2.3 on 2023-07-27 07:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0019_failedloginattempt"),
    ]

    operations = [
        migrations.AlterField(
            model_name="code",
            name="number",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
