# Generated by Django 4.2.3 on 2023-07-24 11:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("employee_dashboard", "0018_paycheque_gross_month_salary"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="paycheque",
            name="annual_income",
        ),
        migrations.AlterField(
            model_name="paycheque",
            name="employee",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="employee_dashboard.userprofile",
            ),
        ),
    ]
