# Generated by Django 4.2.3 on 2023-07-24 12:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("employee_dashboard", "0019_remove_paycheque_annual_income_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="paycheque",
            name="employee",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
