# Generated by Django 4.2.3 on 2023-07-23 05:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("attendence", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="attendencetable",
            old_name="attendence_data",
            new_name="absent_data",
        ),
        migrations.AddField(
            model_name="attendencetable",
            name="present_data",
            field=models.JSONField(default=1),
            preserve_default=False,
        ),
    ]
