# Generated by Django 4.2.3 on 2023-07-23 15:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "attendence",
            "0002_rename_attendence_data_attendencetable_absent_data_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="attendencetable",
            name="absent_data",
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name="attendencetable",
            name="present_data",
            field=models.JSONField(default=list),
        ),
    ]
