# Generated by Django 4.2.3 on 2023-07-25 16:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("attendence", "0003_alter_attendencetable_absent_data_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="attendencetable",
            name="absent_data",
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
