# Generated by Django 4.2.3 on 2023-07-27 14:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("attendence", "0004_alter_attendencetable_absent_data"),
    ]

    operations = [
        migrations.AlterField(
            model_name="attendencetable",
            name="present_data",
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
